# Generated by Django 3.0.5 on 2020-04-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=150)),
                ('price', models.TextField(max_length=150)),
                ('area', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Author Yu Zhao',
            },
        ),
    ]
